### ISSUE TITLE
Buggy behavior with multiple nested frames

### ISSUE THREAD

**Issue by antosart** [w3c/webappsec-cspee#26]
--- Copied from https://github.com/w3c/webappsec-csp/issues/558. ---

Originally pointed out at: https://bugs.chromium.org/p/chromium/issues/detail?id=1263288#c10

@antosart I couldn't find an existing case file so am creating one here.

Take the following set up:

from: http://trusted.test/grandparent.php ===>(A)
```<?php
header("Content-Security-Policy:script-src 'strict-dynamic' 'nonce-grandparent'");
?>
<html>
    <head>
        <title>grandfather</title>
    <head>
<body>

<iframe src="http://untrusted.test/parent.php" csp="script-src 'strict-dynamic' 'nonce-required'" style="width:60%;height:60%;"></iframe>
</body>
</html>
```

from: http://untrusted.test/parent.php ===>(B)
```<?php
header("Content-Security-Policy:script-src 'strict-dynamic' 'nonce-parent'");
?>
<html>
    <head>
        <title>parent</title>
    <head>
<body>
    <div id="qdiv"></div>
<script nonce="parent">
qdiv.innerText="hello from parent"

</script>
<iframe id="qiframe" src="./child.php"></iframe>
</body>
</html>
```

from: http://untrusted.test/child.php ===>(C)
```<?php
header("Content-Security-Policy:script-src 'strict-dynamic' 'nonce-child'");
?>
<html>
    <head>
        <title>child</title>
    <head>
<body>
<div id="qdiv"></div>
<script nonce="child">
qdiv.innerText="hello frodm child"
</script>

</body>
</html>
```

**Observations**:

When navigating to A it will attempt to embed cross origin B with the following CSPEE request header:
`
Sec-Required-CSP: script-src 'strict-dynamic' 'nonce-required'
`
Since A and B are cross-origin, `'nonce-required'` acts sort of like a hint that A expects B to implement some form of nonce. 

And since B responds with the following CSP:
`Content-Security-Policy:script-src 'strict-dynamic' 'nonce-parent'"`
A is satisfied with the requirement and allows B to load in the iframe.

Once B loads, it attempts to load C and sends the following CSPEE request header:
`
Sec-Required-CSP: script-src 'strict-dynamic' 'nonce-required'
`
But since B and C are same-origin, despite C sending back a seemingly compliant CSP:
`Content-Security-Policy:script-src 'strict-dynamic' 'nonce-child'`

B will still allow C to load but C is unable to run javascript despite being 'blessed' by a proper nonce that it defined, which is 'child'. This is what I understand per https://bugs.chromium.org/p/chromium/issues/detail?id=1263288#c3

**Solution**

The main workaround here is to simply serve C from a cross-origin (as it relates to B) URL. 
The problem is that this may not work as a solution for all scenarios. 

**Problems**
Assuming we must keep C same origin as B: 

No 'nonce' value works when put into the script of C (so long as C is setting its own CSP). I tried setting C's nonce to: 'grandparent', 'parent', 'required' and 'child' and none of them work which seems odd.

If I remove the CSP response from C, the only nonce value that works is: 'required' which remember, will never be a real nonce and is only used in CSPEE to hint to embeddee that some nonce should be used. Also the fact we are removing CSP means C can now be loaded in normal main frame and unless the server side is checking for this it will serve it without a CSP which is unsecure (assuming they try to fix this bug that way)

I expected that C would still be considered cross-origin if the `iframe[sandbox]` attribute was present. That is not the case despite technically C frame is considered 'cross-origin' from B perspective when B tries to access sandboxed C js window.

**Proposal**

Allow same-origin CSPEE to behave like cross-origin IFF:
1. B embeds same origin C with another `iframe[csp]` attribute of its own
2. (and/or) B embeds same origin C with `iframe[sandbox]` attribute set

**Comment by antosart** [comment]
One idea could be to always check whether the child's CSP is subsumed by the iframe's `csp` attribute. If it is, we could discard the iframe's `csp` attribute and simply apply the child's CSPs. This would match the cross-origin case for subsumed CSPs and probably sound more natural.

If the child's CSP is not subsumed, and only if the child is same-origin, we could simply enforce the `csp` attribute on the child, as we are doing now.

I have the impression this could save the good part of the existing behaviour while addressing the weirdness you are reporting.

**Comment by qabandi** [comment]
That sounds good, what would be the next steps here to get this change?

**Comment by antosart** [comment]
cc @ArthurSonzogni @camillelamy

**Comment by qabandi** [comment]
Friendly ping

**Comment by camillelamy** [comment]
@arturjanc do you think this makes sense with regard to the nonce?

**Comment by qabandi** [comment]
@camillelamy Do you mean the part "No 'nonce' value works when put into the script of C (so long as C is setting its own CSP). I tried setting C's nonce to: 'grandparent', 'parent', 'required' and 'child' and none of them work which seems odd." this definitely seems like a bug.

**Comment by arturjanc** [comment]
I'm not an expert on CSPEE, but @antosart's proposal [above](https://github.com/w3c/webappsec-cspee/issues/26#issuecomment-1206485007) sounds okay to me.

As a bit of a side note, looking at https://w3c.github.io/webappsec-cspee/#origin-allowed I'm somewhat worried that for the same-origin case we apply the policy from the `csp` attribute without any opt-in. In cases where there's an injection, but script execution is successfully prevented by CSP, this gives the attacker granular control over the resources loaded by the same-origin frame; this may allow interesting scriptless attacks, e.g. disabling a particular script with security functionality but otherwise allowing the frame to render as usual. (This isn't directly relevant to the current bug, I just wanted to make a note of it somewhere)

**Comment by camillelamy** [comment]
@letitz FYI

**Comment by qabandi** [comment]
Hello all! So what are the next steps for me to get this change landed? @arturjanc Is there a document I can read that explains this processm I assume this is a bug in the spec? But have no idea how to proceed and ensure this gets addressed.

**Comment by arturjanc** [comment]
I'd defer to @antosart and @letitz who are more familiar with the CSP:EE spec and might have a preference for the changes we'd want to introduce here.

@shhnjk

**Comment by shhnjk** [comment]
I think the same-origin behavior is worth unshipping. See this year's [Google CTF challenge](https://github.com/google/google-ctf/blob/master/2023/web-biohazard/solution/README.md) where the `csp` attribute was used to remove global variable, and therefore it lead to XSS.

I'll try adding a histogram to see if we can safely remove the same-origin behavior, as CSPEE is used very widely (i.e. [~13% of page load](https://mitigation.supply/)).

**Comment by antosart** [comment]
One intermediate step could also be to stop considering same-origin a frame that is same-origin with an ancestor, if there is an ancestor in between which is cross-origin (e.g. originA > originB > originA). That should solve the XSS @shhnjk points out.

**Comment by shhnjk** [comment]
I think we don't need to care about origins in blanket enforcement at all. Is there any concern with that change?

**Comment by antosart** [comment]
You mean completely removing point 2. of [blanket enforcement](https://w3c.github.io/webappsec-cspee/#origin-allowed)? Sounds fine to me.

However, since you were mentioning usage: if that turns out to be a problem, we could reduce the scope to the case originA > originB > originA.

**Comment by shhnjk** [comment]
Sounds good!

**Comment by shhnjk** [comment]
Same-origin blanket enforcement is only enforced on [~0.000015% of page loads](https://chromestatus.com/metrics/feature/timeline/popularity/4599) in Chrome. Therefore, I'll work on removing this.
